# Generated by Django 5.0.4 on 2024-04-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0002_alter_comment_options'),
        ('core_user', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_comment.comment'),
        ),
    ]
