# Generated by Django 5.0.4 on 2024-04-26 15:55

import apps.core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0006_user_comments_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.user.models.user_directory_path),
        ),
    ]
