# Generated by Django 5.0.4 on 2024-04-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0002_alter_comment_options'),
        ('core_post', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='core_post.post'),
        ),
    ]
